import { boardOptions, displayBoard } from "./board";
import { escapeAttr, escapeHtml, highlightText } from "./filters";
import { getHighlightGroups } from "./posts";
import { formatBeijingTime } from "./time";
import type { Env, PageData, Post, User } from "./types";
import { styles } from "./styles";

function pageUrl(page: number, data: PageData): string {
  const params = new URLSearchParams();
  if (page > 1) params.set("page", String(page));
  if (data.board) params.set("board", data.board);
  if (data.query) params.set("q", data.query);
  const qs = params.toString();
  return `/${qs ? `?${qs}` : ""}`;
}

function pager(data: PageData): string {
  const pages = [data.page, data.page + 1, data.page + 2, data.page + 3].filter((p) => p <= data.totalPages);
  return `<nav class="pager"><a class="page" href="${pageUrl(Math.max(1, data.page - 1), data)}">上一页</a>${pages.map((p) => `<a class="page ${p === data.page ? "current" : ""}" href="${pageUrl(p, data)}">${p}</a>`).join("")}<a class="page" href="${pageUrl(Math.min(data.totalPages, data.page + 1), data)}">下一页</a></nav>`;
}

function renderPost(post: Post, groups: Awaited<ReturnType<typeof getHighlightGroups>>): string {
  const link = escapeAttr(post.link);
  return `<article class="card ${post.is_read ? "read" : ""}" data-post-id="${post.id}"><a class="card-overlay" href="${link}" target="_blank" rel="noreferrer" aria-label="打开帖子"></a><div class="title"><a class="title-link" href="${link}" target="_blank" rel="noreferrer">${highlightText(post.title, groups)}</a></div><div class="body">${post.content_html}</div><div class="meta"><button class="author" data-copy="${escapeAttr(post.author || "")}">${escapeHtml(post.author || "")}</button><div class="board">${escapeHtml(displayBoard(post.board_key))}</div><time class="time">${escapeHtml(formatBeijingTime(post.published_at))}</time></div></article>`;
}

export async function renderHome(env: Env, user: User | null, data: PageData, admin: { adminSecretConfigured: boolean; adminAuthenticated: boolean }): Promise<Response> {
  const groups = await getHighlightGroups(env, user);
  const boardSelect = `<select name="board">${boardOptions.map(([value, label]) => `<option value="${escapeAttr(value)}" ${value === data.board ? "selected" : ""}>${label}</option>`).join("")}</select>`;
  const empty = data.syncError ? `<p class="muted">暂无帖子。RSS 获取失败：${escapeHtml(data.syncError)}。请打开 <a href="/api/rss-test">/api/rss-test</a> 查看请求测试结果。</p>` : `<p class="muted">暂无帖子</p>`;
  const adminNotice = adminNoticeHtml(admin);
  const github = `<footer class="footer"><a class="github-link" href="https://github.com/sfhgknsdfksdlf/nodeseek-rss-reader" target="_blank" rel="noreferrer" aria-label="GitHub nodeseek-rss-reader"><svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path fill="currentColor" d="M12 2C6.48 2 2 6.58 2 12.26c0 4.53 2.87 8.37 6.84 9.73.5.09.68-.22.68-.49 0-.24-.01-.88-.01-1.73-2.78.62-3.37-1.37-3.37-1.37-.45-1.18-1.11-1.49-1.11-1.49-.91-.64.07-.63.07-.63 1 .07 1.53 1.06 1.53 1.06.89 1.56 2.34 1.11 2.91.85.09-.66.35-1.11.63-1.37-2.22-.26-4.56-1.14-4.56-5.07 0-1.12.39-2.03 1.03-2.75-.1-.26-.45-1.3.1-2.71 0 0 .84-.28 2.75 1.05A9.3 9.3 0 0 1 12 6.99c.85 0 1.7.12 2.5.35 1.9-1.33 2.74-1.05 2.74-1.05.55 1.41.2 2.45.1 2.71.64.72 1.03 1.63 1.03 2.75 0 3.94-2.34 4.8-4.57 5.06.36.32.68.95.68 1.92 0 1.38-.01 2.5-.01 2.84 0 .27.18.59.69.49A10.12 10.12 0 0 0 22 12.26C22 6.58 17.52 2 12 2Z"/></svg><span>nodeseek-rss-reader</span><span id="githubStars" class="muted">★</span></a></footer>`;
  const html = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>NodeSeek RSS Reader</title><link rel="icon" href="/icon.svg"><link rel="manifest" href="/manifest.webmanifest"><style>${styles}</style></head><body><main class="wrap"><header class="top"><a class="brand" href="/">NodeSeek RSS Reader</a><div class="auth">${user ? `<span class="muted hide-sm">${escapeHtml(user.username)}</span><button data-dialog="settings">设置</button><button id="logout">退出</button>` : `<button data-dialog="login">登录</button><button data-dialog="register" class="primary">注册</button>`}</div></header>${adminNotice}<form class="toolbar" action="/" method="get">${boardSelect}<input name="q" value="${escapeAttr(data.query)}" placeholder="正则搜索"><button class="primary">搜索</button></form>${pager(data)}<section>${data.posts.map((p) => renderPost(p, groups)).join("") || empty}</section>${pager(data)}<form class="jump" action="/" method="get"><input name="page" inputmode="numeric" value="${data.page}" aria-label="页码"><input type="hidden" name="board" value="${escapeAttr(data.board)}"><input type="hidden" name="q" value="${escapeAttr(data.query)}"><button>跳转</button></form>${github}</main><div class="nd-jump-group"><button class="nd-jump-item" id="toTop" aria-label="到顶部"><svg viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M7.41,15.41L12,10.83L16.59,15.41L18,14L12,8L6,14L7.41,15.41Z" /></svg></button><button class="nd-jump-item" id="toBottom" aria-label="到底部"><svg viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" /></svg></button></div>${dialogs(user)}<div id="toast" class="toast"></div><script>${clientScript()}</script></body></html>`;
  return new Response(html, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" } });
}

function adminNoticeHtml(admin: { adminSecretConfigured: boolean; adminAuthenticated: boolean }): string {
  if (admin.adminAuthenticated) return "";
  if (!admin.adminSecretConfigured) return `<section class="admin-notice" id="adminNotice"><div><b>管理员功能未启用</b><p>如需网页配置发件邮箱、Brevo、Telegram 和保留天数，请在 Cloudflare Worker Secrets 添加 <code class="copy-code" data-copy="ADMIN_SECRET">ADMIN_SECRET</code> <button data-copy="ADMIN_SECRET">复制</button>。</p><details><summary>查看配置步骤</summary><ol><li>打开 Cloudflare 控制台。</li><li>进入「Workers 和 Pages / Workers & Pages」。</li><li>点击当前 Worker：<code>nodeseek-rss-reader</code>。</li><li>打开「设置 / Settings」。</li><li>打开「变量和机密 / Variables and Secrets」。</li><li>点击「添加 / Add」。</li><li>类型选择「机密 / Secret」。</li><li>「变量名称 / Variable name」填 <code class="copy-code" data-copy="ADMIN_SECRET">ADMIN_SECRET</code> <button data-copy="ADMIN_SECRET">复制</button>。</li><li>「值 / Value」填 32-64 位小写字母数字，例如 <code class="copy-code" data-copy="r7m4qp9vz2kx8nw6ta3yh5bc1ls0defg">r7m4qp9vz2kx8nw6ta3yh5bc1ls0defg</code> <button data-copy="r7m4qp9vz2kx8nw6ta3yh5bc1ls0defg">复制</button>。</li><li>保存前复制并安全保存这个值，Cloudflare 保存后不会再显示明文。</li><li>点击输入框下方空白处，让「保存 / Save」按钮变亮。</li><li>点击「保存 / Save」；如果弹出部署选择，点击「不部署 / Do not deploy」即可生效。</li><li>打开 <code>/admin?token=你的ADMIN_SECRET</code>，并保存完整链接为书签。</li></ol><p>推荐只使用小写字母和数字。URL 的域名不区分大小写，但 <code>token</code> 参数值区分大小写；不推荐特殊字符。</p></details></div><button data-dismiss-admin>关闭</button></section>`;
  return `<section class="admin-notice" id="adminNotice"><div><b>管理员配置</b><p>如需修改发件配置，请打开独立管理页：<code>/admin?token=你的ADMIN_SECRET</code>。管理链接包含 SECRET，请保存完整链接为书签且不要分享。</p></div><button data-dismiss-admin>关闭</button></section>`;
}

function dialogs(user: User | null): string {
  return `<dialog id="login"><div class="panel-head"><b>登录</b><button data-close>关闭</button></div><form class="grid" data-auth="/api/auth/login"><input name="username" placeholder="用户名"><input name="password" type="password" placeholder="密码"><button class="primary">登录</button></form></dialog><dialog id="register"><div class="panel-head"><b>注册</b><button data-close>关闭</button></div><form class="grid" data-auth="/api/auth/register"><input name="username" placeholder="用户名"><input name="password" type="password" placeholder="密码至少 6 位"><button class="primary">注册</button></form></dialog><dialog id="settings"><div class="panel-head"><b>设置</b><button data-close>关闭</button></div>${user ? settingsHtml() : ""}</dialog>`;
}

function settingsHtml(): string {
  return `<div class="tabs"><button class="tab active" data-tab="highlights">高亮</button><button class="tab" data-tab="blocks">屏蔽</button><button class="tab" data-tab="subs">订阅</button></div><div id="settingsBody" class="grid muted">加载中</div>`;
}

function clientScript(): string {
  return String.raw`
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1800)}
async function api(method,url,body){const r=await fetch(url,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});if(!r.ok){let e='失败';try{e=(await r.json()).error||e}catch{}toast(e)}return r}
$$('[data-dialog]').forEach(b=>b.onclick=()=>{document.getElementById(b.dataset.dialog).showModal(); if(b.dataset.dialog==='settings') loadTab(window.settingTab||'highlights')});
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$$('[data-auth]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const r=await api('POST',f.dataset.auth,Object.fromEntries(new FormData(f)));if(r.ok) location.reload()});
$('#logout')?.addEventListener('click',async()=>{await fetch('/api/auth/logout',{method:'POST'});location.reload()});
if(localStorage.getItem('hideAdminNotice'))$('#adminNotice')?.remove();$('[data-dismiss-admin]')?.addEventListener('click',()=>{localStorage.setItem('hideAdminNotice','1');$('#adminNotice')?.remove()});
const boardSelect=$('.toolbar select[name="board"]');boardSelect?.addEventListener('change',()=>{boardSelect.form.requestSubmit?boardSelect.form.requestSubmit():boardSelect.form.submit()});
function markRead(c){const id=c.dataset.postId;c.classList.add('read');if(id){localStorage.setItem('read:'+id,'1');fetch('/api/read-state',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({postId:Number(id)})}).catch(()=>{})}}
$$('.card').forEach(c=>{const id=c.dataset.postId;if(id&&localStorage.getItem('read:'+id))c.classList.add('read');c.querySelectorAll('.card-overlay,.title-link').forEach(a=>a.addEventListener('click',()=>markRead(c)))});
$$('[data-copy]').forEach(b=>{b.addEventListener('pointerdown',e=>e.stopPropagation());b.onclick=async e=>{e.preventDefault();e.stopPropagation();const v=b.dataset.copy||'';try{await navigator.clipboard.writeText(v);b.classList.add('copied');setTimeout(()=>b.classList.remove('copied'),500);toast('已复制：'+v)}catch{toast('复制失败')}}});
$('#toTop').onclick=()=>scrollTo({top:0,behavior:'smooth'});$('#toBottom').onclick=()=>scrollTo({top:document.body.scrollHeight,behavior:'smooth'});
fetch('https://api.github.com/repos/sfhgknsdfksdlf/nodeseek-rss-reader').then(r=>r.ok?r.json():null).then(d=>{if(d&&Number.isFinite(d.stargazers_count))$('#githubStars').textContent='★ '+d.stargazers_count}).catch(()=>{});
$$('[data-tab]').forEach(b=>b.onclick=()=>loadTab(b.dataset.tab));
function setActive(tab){window.settingTab=tab;$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}
function tools(type){return '<div class="toolrow"><button data-import="'+type+'">导入</button><button data-export="'+type+'">导出</button></div>'}
async function loadTab(tab){setActive(tab);const box=$('#settingsBody');box.className='grid';box.innerHTML='<p class="muted">加载中</p>';if(tab==='highlights')return loadHighlights();if(tab==='blocks')return loadBlocks();return loadSubs()}
function chip(text,attrs=''){return '<span class="chip"><span>'+esc(text)+'</span><button class="chip-x" '+attrs+'>×</button></span>'}
function keywordRows(items, attrs){return '<div class="keywords">'+items.slice().reverse().map(item=>'<span class="keyword-cell">'+chip(item.label,attrs(item))+'</span>').join('')+'</div>'}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
window.settingData={highlights:[],blocks:[],subscriptions:[]};
function renderHighlights(){const data=window.settingData.highlights;const box=$('#settingsBody');box.innerHTML=tools('highlights')+data.map(g=>'<div class="rule"><div class="group-title"><input class="color-input" type="color" value="'+esc(g.color)+'" data-color="'+g.id+'"><b>'+esc(g.name)+'</b><button data-clear="'+g.id+'">清空</button><button class="danger" data-del-group="'+g.id+'">删除</button></div><div class="keyword-panel">'+keywordRows(g.patterns.map(p=>({label:p})) ,item=>'data-rm-highlight="'+g.id+'" data-pattern="'+esc(item.label)+'"')+'<form class="keyword-add-row" data-add-rule="'+g.id+'"><input name="pattern" placeholder="关键字正则"><button class="primary">添加</button></form></div></div>').join('')+'<form class="keyword-add-row add-bottom" id="newGroup"><input name="name" placeholder="分组名"><button class="primary">添加分组</button></form>';$('#newGroup').onsubmit=async e=>{e.preventDefault();const name=Object.fromEntries(new FormData(e.target)).name;if(!String(name||'').trim())return;const temp={id:'tmp-'+Date.now(),name:String(name),color:'#ffe066',patterns:[]};window.settingData.highlights.push(temp);renderHighlights();const r=await api('POST','/api/highlight-groups',{name});if(r.ok){const saved=await r.json();Object.assign(temp,saved);renderHighlights()}else loadHighlights()}}
async function loadHighlights(){window.settingData.highlights=await (await fetch('/api/highlight-groups')).json();renderHighlights()}
function renderBlocks(){const data=window.settingData.blocks;$('#settingsBody').innerHTML=tools('blocks')+'<div class="keyword-panel">'+keywordRows(data.map(r=>({label:r.pattern,id:r.id})),item=>'data-del-block="'+item.id+'"')+'<form class="keyword-add-row add-bottom" id="newBlock"><input name="pattern" placeholder="屏蔽正则"><button class="primary">添加</button></form></div>';$('#newBlock').onsubmit=async e=>{e.preventDefault();const pattern=Object.fromEntries(new FormData(e.target)).pattern;if(!String(pattern||'').trim())return;const temp={id:'tmp-'+Date.now(),pattern:String(pattern)};window.settingData.blocks.push(temp);renderBlocks();const r=await api('POST','/api/block-rules',{pattern});if(r.ok){const saved=await r.json();Object.assign(temp,saved);renderBlocks()}else loadBlocks()}}
async function loadBlocks(){window.settingData.blocks=await (await fetch('/api/block-rules')).json();renderBlocks()}
async function loadSubs(){const data=await (await fetch('/api/subscriptions')).json();$('#settingsBody').innerHTML=tools('subscriptions')+data.map(r=>'<div class="rule row"><span class="chip"><span>'+esc(r.pattern)+'</span></span><button class="danger" data-del-sub="'+r.id+'">删除</button></div>').join('')+'<form class="row add-bottom" id="newSub"><input name="pattern" placeholder="订阅正则"><button class="primary">添加</button></form>';$('#newSub').onsubmit=async e=>{e.preventDefault();await api('POST','/api/subscriptions',Object.fromEntries(new FormData(e.target)));loadSubs()}}
document.addEventListener('submit',async e=>{const f=e.target;if(f.dataset.addRule){e.preventDefault();const g=window.settingData.highlights.find(x=>String(x.id)===String(f.dataset.addRule));const pattern=String(Object.fromEntries(new FormData(f)).pattern||'').trim();if(!g||!pattern)return;g.patterns.push(pattern);renderHighlights();const r=await api('PUT','/api/highlight-groups/'+f.dataset.addRule,{name:g.name,color:g.color,patterns:g.patterns});if(!r.ok)loadHighlights()}});
document.addEventListener('change',async e=>{const t=e.target;if(t.dataset.color){const g=window.settingData.highlights.find(x=>String(x.id)===String(t.dataset.color));if(!g)return;g.color=t.value;renderHighlights();const r=await api('PUT','/api/highlight-groups/'+t.dataset.color,{name:g.name,color:g.color,patterns:g.patterns});if(r.ok)toast('颜色已保存');else loadHighlights()}});
document.addEventListener('click',async e=>{const t=e.target;if(t.dataset.clear){const g=window.settingData.highlights.find(x=>String(x.id)===String(t.dataset.clear));if(g)g.patterns=[];renderHighlights();const r=await api('POST','/api/highlight-groups/'+t.dataset.clear+'/clear');if(!r.ok)loadHighlights()}if(t.dataset.delGroup){window.settingData.highlights=window.settingData.highlights.filter(x=>String(x.id)!==String(t.dataset.delGroup));renderHighlights();const r=await api('DELETE','/api/highlight-groups/'+t.dataset.delGroup);if(!r.ok)loadHighlights()}if(t.dataset.rmHighlight){const g=window.settingData.highlights.find(x=>String(x.id)===String(t.dataset.rmHighlight));if(g)g.patterns=g.patterns.filter(p=>p!==t.dataset.pattern);renderHighlights();const r=await api('PUT','/api/highlight-groups/'+t.dataset.rmHighlight,{name:g.name,color:g.color,patterns:g.patterns});if(!r.ok)loadHighlights()}if(t.dataset.delBlock){const old=window.settingData.blocks;window.settingData.blocks=old.filter(x=>String(x.id)!==String(t.dataset.delBlock));renderBlocks();const r=await api('DELETE','/api/block-rules/'+t.dataset.delBlock);if(!r.ok){window.settingData.blocks=old;renderBlocks()}}if(t.dataset.delSub){await api('DELETE','/api/subscriptions/'+t.dataset.delSub);loadSubs()}if(t.dataset.export){await exportRules(t.dataset.export)}if(t.dataset.import){await importRules(t.dataset.import)}});
async function exportRules(type){let out;if(type==='highlights'){const g=await (await fetch('/api/highlight-groups')).json();out={type,version:1,groups:g.map(x=>({name:x.name,color:x.color,patterns:x.patterns}))}}else if(type==='blocks'){const r=await (await fetch('/api/block-rules')).json();out={type,version:1,patterns:r.map(x=>x.pattern)}}else{const r=await (await fetch('/api/subscriptions')).json();out={type,version:1,rules:r.map(x=>({pattern:x.pattern,sendEmail:!!x.send_email,sendTelegram:!!x.send_telegram}))}}await navigator.clipboard.writeText(JSON.stringify(out,null,2));toast('规则已复制')}
async function importRules(type){const text=prompt('粘贴JSON，覆盖导入会删除当前tab现有规则');if(!text)return;if(!confirm('覆盖导入会删除当前tab的现有规则，确认继续？'))return;let data;try{data=JSON.parse(text)}catch{toast('JSON格式错误');return}const url=type==='highlights'?'/api/import/highlights':type==='blocks'?'/api/import/blocks':'/api/import/subscriptions';const r=await api('POST',url,data);if(r.ok){toast('导入完成');loadTab(window.settingTab)}}
`;
}
