import { boardOptions, displayBoard } from "./board";
import { escapeAttr, escapeHtml, highlightText } from "./filters";
import { getHighlightGroups } from "./posts";
import { formatBeijingTime } from "./time";
import type { Env, PageData, Post, User } from "./types";
import { styles } from "./styles";

function pageUrl(page: number, data: PageData): string {
  const params = new URLSearchParams();
  if (page > 1) params.set("page", String(page));
  if (data.board) params.set("board", data.board);
  if (data.query) params.set("q", data.query);
  const qs = params.toString();
  return `/${qs ? `?${qs}` : ""}`;
}

function pager(data: PageData): string {
  const pages = [data.page, data.page + 1, data.page + 2, data.page + 3].filter((p) => p <= data.totalPages);
  return `<nav class="pager"><a class="page" href="${pageUrl(Math.max(1, data.page - 1), data)}">上一页</a>${pages.map((p) => `<a class="page ${p === data.page ? "current" : ""}" href="${pageUrl(p, data)}">${p}</a>`).join("")}<a class="page" href="${pageUrl(Math.min(data.totalPages, data.page + 1), data)}">下一页</a></nav>`;
}

function renderPost(post: Post, groups: Awaited<ReturnType<typeof getHighlightGroups>>): string {
  return `<article class="card ${post.is_read ? "read" : ""}" data-post-id="${post.id}" data-open="/post/${post.id}/open"><div class="title">${highlightText(post.title, groups)}</div><div class="body">${post.content_html}</div><div class="meta"><button class="author" data-copy="${escapeAttr(post.author || "")}">${escapeHtml(post.author || "")}</button><div class="board">${escapeHtml(displayBoard(post.board_key))}</div><time class="time">${escapeHtml(formatBeijingTime(post.published_at))}</time></div></article>`;
}

export async function renderHome(env: Env, user: User | null, data: PageData): Promise<Response> {
  const groups = await getHighlightGroups(env, user);
  const boardSelect = `<select name="board">${boardOptions.map(([value, label]) => `<option value="${escapeAttr(value)}" ${value === data.board ? "selected" : ""}>${label}</option>`).join("")}</select>`;
  const empty = data.syncError ? `<p class="muted">暂无帖子。RSS 获取失败：${escapeHtml(data.syncError)}。请打开 <a href="/api/rss-test">/api/rss-test</a> 查看请求测试结果。</p>` : `<p class="muted">暂无帖子</p>`;
  const html = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>NodeSeek RSS Reader</title><link rel="icon" href="/icon.svg"><link rel="manifest" href="/manifest.webmanifest"><style>${styles}</style></head><body><main class="wrap"><header class="top"><a class="brand" href="/">NodeSeek RSS Reader</a><div class="auth">${user ? `<span class="muted hide-sm">${escapeHtml(user.username)}</span><button data-dialog="settings">设置</button><button id="logout">退出</button>` : `<button data-dialog="login">登录</button><button data-dialog="register" class="primary">注册</button>`}</div></header><form class="toolbar" action="/" method="get">${boardSelect}<input name="q" value="${escapeAttr(data.query)}" placeholder="正则搜索"><button class="primary">搜索</button></form>${pager(data)}<section>${data.posts.map((p) => renderPost(p, groups)).join("") || empty}</section>${pager(data)}<form class="jump" action="/" method="get"><input name="page" inputmode="numeric" value="${data.page}" aria-label="页码"><input type="hidden" name="board" value="${escapeAttr(data.board)}"><input type="hidden" name="q" value="${escapeAttr(data.query)}"><button>跳转</button></form></main><div class="float"><button id="toTop" aria-label="到顶部">⌃</button><button id="toBottom" aria-label="到底部">⌄</button></div>${dialogs(user)}<div id="toast" class="toast"></div><script>${clientScript()}</script></body></html>`;
  return new Response(html, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" } });
}

function dialogs(user: User | null): string {
  return `<dialog id="login"><div class="panel-head"><b>登录</b><button data-close>关闭</button></div><form class="grid" data-auth="/api/auth/login"><input name="username" placeholder="用户名"><input name="password" type="password" placeholder="密码"><button class="primary">登录</button></form></dialog><dialog id="register"><div class="panel-head"><b>注册</b><button data-close>关闭</button></div><form class="grid" data-auth="/api/auth/register"><input name="username" placeholder="用户名"><input name="password" type="password" placeholder="密码至少 6 位"><button class="primary">注册</button></form></dialog><dialog id="settings"><div class="panel-head"><b>设置</b><button data-close>关闭</button></div>${user ? settingsHtml() : ""}</dialog>`;
}

function settingsHtml(): string {
  return `<div class="tabs"><button class="tab active" data-tab="highlights">高亮</button><button class="tab" data-tab="blocks">屏蔽</button><button class="tab" data-tab="subs">订阅</button><button class="tab" data-tab="admin">管理员</button></div><div id="settingsBody" class="grid muted">加载中</div>`;
}

function clientScript(): string {
  return String.raw`
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1800)}
async function api(method,url,body){const r=await fetch(url,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});if(!r.ok){let e='失败';try{e=(await r.json()).error||e}catch{}toast(e)}return r}
$$('[data-dialog]').forEach(b=>b.onclick=()=>{document.getElementById(b.dataset.dialog).showModal(); if(b.dataset.dialog==='settings') loadTab(window.settingTab||'highlights')});
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$$('[data-auth]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const r=await api('POST',f.dataset.auth,Object.fromEntries(new FormData(f)));if(r.ok) location.reload()});
$('#logout')?.addEventListener('click',async()=>{await fetch('/api/auth/logout',{method:'POST'});location.reload()});
const boardSelect=$('.toolbar select[name="board"]');boardSelect?.addEventListener('change',()=>{boardSelect.form.requestSubmit?boardSelect.form.requestSubmit():boardSelect.form.submit()});
$$('.card').forEach(c=>{const id=c.dataset.postId;if(id&&localStorage.getItem('read:'+id))c.classList.add('read');c.addEventListener('click',e=>{if(e.target.closest('[data-copy]'))return;c.classList.add('read');if(id){localStorage.setItem('read:'+id,'1');fetch('/api/read-state',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({postId:Number(id)})}).catch(()=>{})}window.open(c.dataset.open,'_blank','noopener')})});
$$('[data-copy]').forEach(b=>b.onclick=async e=>{e.stopPropagation();const v=b.dataset.copy||'';try{await navigator.clipboard.writeText(v);toast('已复制用户名：'+v)}catch{toast('复制失败')}});
$('#toTop').onclick=()=>scrollTo({top:0,behavior:'smooth'});$('#toBottom').onclick=()=>scrollTo({top:document.body.scrollHeight,behavior:'smooth'});
$$('[data-tab]').forEach(b=>b.onclick=()=>loadTab(b.dataset.tab));
function setActive(tab){window.settingTab=tab;$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}
function tools(type){return '<div class="toolrow"><button data-import="'+type+'">导入</button><button data-export="'+type+'">导出</button></div>'}
async function loadTab(tab){setActive(tab);const box=$('#settingsBody');box.className='grid';box.innerHTML='<p class="muted">加载中</p>';if(tab==='highlights')return loadHighlights();if(tab==='blocks')return loadBlocks();if(tab==='subs')return loadSubs();return loadAdmin()}
function chip(text,attrs=''){return '<span class="chip"><span>'+esc(text)+'</span><button class="chip-x" '+attrs+'>×</button></span>'}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function loadHighlights(){const data=await (await fetch('/api/highlight-groups')).json();const box=$('#settingsBody');box.innerHTML=tools('highlights')+data.map(g=>'<div class="rule"><div class="group-title"><input class="color-input" type="color" value="'+esc(g.color)+'" data-color="'+g.id+'"><b>'+esc(g.name)+'</b><button data-clear="'+g.id+'">清空</button><button class="danger" data-del-group="'+g.id+'">删除</button></div><div class="keywords">'+g.patterns.map(p=>chip(p,'data-rm-highlight="'+g.id+'" data-pattern="'+esc(p)+'"')).join('')+'</div><form class="row" data-add-rule="'+g.id+'"><input name="pattern" placeholder="关键字正则"><button class="primary">添加</button></form></div>').join('')+'<form class="row add-bottom" id="newGroup"><input name="name" placeholder="分组名"><input class="color-input" name="color" type="color" value="#ffe066"><button class="primary">添加分组</button></form>';$('#newGroup').onsubmit=async e=>{e.preventDefault();await api('POST','/api/highlight-groups',Object.fromEntries(new FormData(e.target)));loadHighlights()}}
async function loadBlocks(){const data=await (await fetch('/api/block-rules')).json();$('#settingsBody').innerHTML=tools('blocks')+'<div class="keywords">'+data.map(r=>chip(r.pattern,'data-del-block="'+r.id+'"')).join('')+'</div><form class="row add-bottom" id="newBlock"><input name="pattern" placeholder="屏蔽正则"><button class="primary">添加</button></form>';$('#newBlock').onsubmit=async e=>{e.preventDefault();await api('POST','/api/block-rules',Object.fromEntries(new FormData(e.target)));loadBlocks()}}
async function loadSubs(){const data=await (await fetch('/api/subscriptions')).json();$('#settingsBody').innerHTML=tools('subscriptions')+data.map(r=>'<div class="rule row"><span class="chip"><span>'+esc(r.pattern)+'</span></span><button class="danger" data-del-sub="'+r.id+'">删除</button></div>').join('')+'<form class="row add-bottom" id="newSub"><input name="pattern" placeholder="订阅正则"><button class="primary">添加</button></form>';$('#newSub').onsubmit=async e=>{e.preventDefault();await api('POST','/api/subscriptions',Object.fromEntries(new FormData(e.target)));loadSubs()}}
async function loadAdmin(){const r=await fetch('/api/admin/settings');if(!r.ok){$('#settingsBody').innerHTML='<div class="rule"><p>未认证管理员或 ADMIN_SECRET 未配置。</p><p>请在 Cloudflare Secrets 添加 <code>ADMIN_SECRET</code>，然后访问 <code>/admin?token=你的ADMIN_SECRET</code>。请保存该管理入口为书签，管理员会话 7 天后需要重新打开书签认证。</p></div>';return}const s=await r.json();$('#settingsBody').innerHTML='<form class="grid" id="adminForm"><label>Brevo API Key<input name="brevoApiKey" placeholder="'+(s.brevoApiKeyConfigured?'已配置，留空不修改':'未配置')+'"></label><label>发件邮箱<input name="mailFrom" value="'+esc(s.mailFrom)+'"></label><label>发件人名称<input name="mailFromName" value="'+esc(s.mailFromName)+'"></label><label>Telegram Bot Token<input name="telegramBotToken" placeholder="'+(s.telegramBotTokenConfigured?'已配置，留空不修改':'未配置')+'"></label><label>已读保留天数<input name="readStateRetentionDays" type="number" min="1" max="3650" value="'+s.readStateRetentionDays+'"></label><label>RSS帖子保留天数<input name="postRetentionDays" type="number" min="1" max="3650" value="'+s.postRetentionDays+'"></label><label>推送日志保留天数<input name="pushLogRetentionDays" type="number" min="1" max="3650" value="'+s.pushLogRetentionDays+'"></label><button class="primary">保存管理员配置</button><button type="button" id="adminLogout">退出管理员</button><p class="muted">请保存 <code>/admin?token=你的ADMIN_SECRET</code> 为书签，管理员会话 7 天后需要重新打开书签认证。</p></form>';$('#adminForm').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.readStateRetentionDays=Number(body.readStateRetentionDays);body.postRetentionDays=Number(body.postRetentionDays);body.pushLogRetentionDays=Number(body.pushLogRetentionDays);const rr=await api('PUT','/api/admin/settings',body);if(rr.ok)toast('管理员配置已保存')};$('#adminLogout').onclick=async()=>{await api('POST','/api/admin/logout');loadAdmin()}}
document.addEventListener('submit',async e=>{const f=e.target;if(f.dataset.addRule){e.preventDefault();const groups=await (await fetch('/api/highlight-groups')).json();const g=groups.find(x=>String(x.id)===String(f.dataset.addRule));const pattern=Object.fromEntries(new FormData(f)).pattern;await api('PUT','/api/highlight-groups/'+f.dataset.addRule,{name:g.name,color:g.color,patterns:[...g.patterns,pattern]});loadHighlights()}});
document.addEventListener('change',async e=>{const t=e.target;if(t.dataset.color){const groups=await (await fetch('/api/highlight-groups')).json();const g=groups.find(x=>String(x.id)===String(t.dataset.color));await api('PUT','/api/highlight-groups/'+t.dataset.color,{name:g.name,color:t.value,patterns:g.patterns});toast('颜色已保存');loadHighlights()}});
document.addEventListener('click',async e=>{const t=e.target;if(t.dataset.clear){await api('POST','/api/highlight-groups/'+t.dataset.clear+'/clear');loadHighlights()}if(t.dataset.delGroup){await api('DELETE','/api/highlight-groups/'+t.dataset.delGroup);loadHighlights()}if(t.dataset.rmHighlight){const groups=await (await fetch('/api/highlight-groups')).json();const g=groups.find(x=>String(x.id)===String(t.dataset.rmHighlight));await api('PUT','/api/highlight-groups/'+t.dataset.rmHighlight,{name:g.name,color:g.color,patterns:g.patterns.filter(p=>p!==t.dataset.pattern)});loadHighlights()}if(t.dataset.delBlock){await api('DELETE','/api/block-rules/'+t.dataset.delBlock);loadBlocks()}if(t.dataset.delSub){await api('DELETE','/api/subscriptions/'+t.dataset.delSub);loadSubs()}if(t.dataset.export){await exportRules(t.dataset.export)}if(t.dataset.import){await importRules(t.dataset.import)}});
async function exportRules(type){let out;if(type==='highlights'){const g=await (await fetch('/api/highlight-groups')).json();out={type,version:1,groups:g.map(x=>({name:x.name,color:x.color,patterns:x.patterns}))}}else if(type==='blocks'){const r=await (await fetch('/api/block-rules')).json();out={type,version:1,patterns:r.map(x=>x.pattern)}}else{const r=await (await fetch('/api/subscriptions')).json();out={type,version:1,rules:r.map(x=>({pattern:x.pattern,sendEmail:!!x.send_email,sendTelegram:!!x.send_telegram}))}}await navigator.clipboard.writeText(JSON.stringify(out,null,2));toast('规则已复制')}
async function importRules(type){const text=prompt('粘贴JSON，覆盖导入会删除当前tab现有规则');if(!text)return;if(!confirm('覆盖导入会删除当前tab的现有规则，确认继续？'))return;let data;try{data=JSON.parse(text)}catch{toast('JSON格式错误');return}const url=type==='highlights'?'/api/import/highlights':type==='blocks'?'/api/import/blocks':'/api/import/subscriptions';const r=await api('POST',url,data);if(r.ok){toast('导入完成');loadTab(window.settingTab)}}
`;
}
